Controllers/THOIKHOABIEUxController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QLTHPT.App_Start;
using QLTHPT.Models;

namespace QLTHPT.Controllers
{
    public class THOIKHOABIEUxController : Controller
    {
        private acomptec_qlthptEntities db = new acomptec_qlthptEntities();

        // GET: THOIKHOABIEUx
        public ActionResult Index()
        {
            var tHOIKHOABIEUx = db.THOIKHOABIEUx.Include(t => t.CANBO).Include(t => t.HOCKY).Include(t => t.LOP).Include(t => t.MONHOC).Include(t => t.THU).Include(t => t.TIETHOC);
            return View(tHOIKHOABIEUx.ToList());
        }

        // GET: THOIKHOABIEUx/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            THOIKHOABIEU tHOIKHOABIEU = db.THOIKHOABIEUx.Find(id);
            if (tHOIKHOABIEU == null)
            {
                return HttpNotFound();
            }
            return View(tHOIKHOABIEU);
        }

        // GET: THOIKHOABIEUx/Create
        public ActionResult Create()
        {
            ViewBag.CANBO_CB_MA = new SelectList(db.CANBOes, "CB_MA", "CB_HOTEN");
            ViewBag.HOCKY_HK_MA = new SelectList(db.HOCKies, "HK_MA", "HK_TEN");
            ViewBag.LOP_LOP_MA = new SelectList(db.LOPs, "LOP_MA", "LOP_TEN");
            ViewBag.MONHOC_MH_MA = new SelectList(db.MONHOCs, "MH_MA", "MH_TEN");
            ViewBag.THU_THU_MA = new SelectList(db.THUs, "THU_MA", "THU_TEN");
            ViewBag.TIETHOC_TH_MA = new SelectList(db.TIETHOCs, "TH_MA", "TH_TEN");
            THOIKHOABIEU obj = new THOIKHOABIEU();
            obj.TKB_MA = CreateID.CreateID_ByteText();
            return View(obj);
        }

        // POST: THOIKHOABIEUx/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TKB_MA,LOP_LOP_MA,MONHOC_MH_MA,THU_THU_MA,TIETHOC_TH_MA,CANBO_CB_MA,HOCKY_HK_MA")] THOIKHOABIEU tHOIKHOABIEU)
        {
            if (ModelState.IsValid)
            {
                db.THOIKHOABIEUx.Add(tHOIKHOABIEU);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CANBO_CB_MA = new SelectList(db.CANBOes, "CB_MA", "CB_HOTEN", tHOIKHOABIEU.CANBO_CB_MA);
            ViewBag.HOCKY_HK_MA = new SelectList(db.HOCKies, "HK_MA", "HK_TEN", tHOIKHOABIEU.HOCKY_HK_MA);
            ViewBag.LOP_LOP_MA = new SelectList(db.LOPs, "LOP_MA", "LOP_TEN", tHOIKHOABIEU.LOP_LOP_MA);
            ViewBag.MONHOC_MH_MA = new SelectList(db.MONHOCs, "MH_MA", "MH_TEN", tHOIKHOABIEU.MONHOC_MH_MA);
            ViewBag.THU_THU_MA = new SelectList(db.THUs, "THU_MA", "THU_TEN", tHOIKHOABIEU.THU_THU_MA);
            ViewBag.TIETHOC_TH_MA = new SelectList(db.TIETHOCs, "TH_MA", "TH_TEN", tHOIKHOABIEU.TIETHOC_TH_MA);
            return View(tHOIKHOABIEU);
        }

        // GET: THOIKHOABIEUx/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            THOIKHOABIEU tHOIKHOABIEU = db.THOIKHOABIEUx.Find(id);
            if (tHOIKHOABIEU == null)
            {
                return HttpNotFound();
            }
            ViewBag.CANBO_CB_MA = new SelectList(db.CANBOes, "CB_MA", "CB_HOTEN", tHOIKHOABIEU.CANBO_CB_MA);
            ViewBag.HOCKY_HK_MA = new SelectList(db.HOCKies, "HK_MA", "HK_TEN", tHOIKHOABIEU.HOCKY_HK_MA);
            ViewBag.LOP_LOP_MA = new SelectList(db.LOPs, "LOP_MA", "LOP_TEN", tHOIKHOABIEU.LOP_LOP_MA);
            ViewBag.MONHOC_MH_MA = new SelectList(db.MONHOCs, "MH_MA", "MH_TEN", tHOIKHOABIEU.MONHOC_MH_MA);
            ViewBag.THU_THU_MA = new SelectList(db.THUs, "THU_MA", "THU_TEN", tHOIKHOABIEU.THU_THU_MA);
            ViewBag.TIETHOC_TH_MA = new SelectList(db.TIETHOCs, "TH_MA", "TH_TEN", tHOIKHOABIEU.TIETHOC_TH_MA);
            return View(tHOIKHOABIEU);
        }

        // POST: THOIKHOABIEUx/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TKB_MA,LOP_LOP_MA,MONHOC_MH_MA,THU_THU_MA,TIETHOC_TH_MA,CANBO_CB_MA,HOCKY_HK_MA")] THOIKHOABIEU tHOIKHOABIEU)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tHOIKHOABIEU).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CANBO_CB_MA = new SelectList(db.CANBOes, "CB_MA", "CB_HOTEN", tHOIKHOABIEU.CANBO_CB_MA);
            ViewBag.HOCKY_HK_MA = new SelectList(db.HOCKies, "HK_MA", "HK_TEN", tHOIKHOABIEU.HOCKY_HK_MA);
            ViewBag.LOP_LOP_MA = new SelectList(db.LOPs, "LOP_MA", "LOP_TEN", tHOIKHOABIEU.LOP_LOP_MA);
            ViewBag.MONHOC_MH_MA = new SelectList(db.MONHOCs, "MH_MA", "MH_TEN", tHOIKHOABIEU.MONHOC_MH_MA);
            ViewBag.THU_THU_MA = new SelectList(db.THUs, "THU_MA", "THU_TEN", tHOIKHOABIEU.THU_THU_MA);
            ViewBag.TIETHOC_TH_MA = new SelectList(db.TIETHOCs, "TH_MA", "TH_TEN", tHOIKHOABIEU.TIETHOC_TH_MA);
            return View(tHOIKHOABIEU);
        }

        // GET: THOIKHOABIEUx/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            THOIKHOABIEU tHOIKHOABIEU = db.THOIKHOABIEUx.Find(id);
            if (tHOIKHOABIEU == null)
            {
                return HttpNotFound();
            }
            return View(tHOIKHOABIEU);
        }

        // POST: THOIKHOABIEUx/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            THOIKHOABIEU tHOIKHOABIEU = db.THOIKHOABIEUx.Find(id);
            db.THOIKHOABIEUx.Remove(tHOIKHOABIEU);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/THOIKHOABIEUx/Create.cshtml
@model QLTHPT.Models.Thoikhoabieu

@{
    ViewBag.Title = "Create";
}

<div class="data-table-area mg-b-15">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <div class="sparkline13-list shadow-reset">
                    <div class="sparkline13-hd">
                        <div class="main-sparkline13-hd">
                            <h4><strong>Tạo Mới</strong></h4>

                        </div>
                    </div>
                    <div class="sparkline13-graph">
                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-horizontal">
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                                <div class="form-horizontal">
                                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                                    <div class="form-group-inner" style="text-align: left;">
                                        <div class="col-md-12" style="text-align: left;">
                                            @Html.LabelFor(model => model.TkbMa, "Mã", htmlAttributes: new { @class = "control-label" })
                                            @Html.EditorFor(model => model.TkbMa, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                                            @Html.ValidationMessageFor(model => model.TkbMa, "", new { @class = "text-danger" })
                                        </div>

                                        <div class="col-md-6">
                                            @Html.LabelFor(model => model.LopLopMa, "Lớp", htmlAttributes: new { @class = "control-label" })
                                            @Html.DropDownList("LopLopMa", null, htmlAttributes: new { @class = "form-control" })
                                            @Html.ValidationMessageFor(model => model.LopLopMa, "", new { @class = "text-danger" })
                                        </div>

                                        <div class="col-md-6">
                                            @Html.LabelFor(model => model.MonhocMhMa, "Môn", htmlAttributes: new { @class = "control-label" })
                                            @Html.DropDownList("MonhocMhMa", null, htmlAttributes: new { @class = "form-control" })
                                            @Html.ValidationMessageFor(model => model.MonhocMhMa, "", new { @class = "text-danger" })
                                        </div>

                                        <div class="col-md-6">
                                            @Html.LabelFor(model => model.ThuThuMa, "Thứ", htmlAttributes: new { @class = "control-label" })
                                            @Html.DropDownList("ThuThuMa", null, htmlAttributes: new { @class = "form-control" })
                                            @Html.ValidationMessageFor(model => model.ThuThuMa, "", new { @class = "text-danger" })
                                        </div>

                                        <div class="col-md-6">
                                            @Html.LabelFor(model => model.TiethocThMa, "Tiết", htmlAttributes: new { @class = "control-label" })
                                            @Html.DropDownList("TiethocThMa", null, htmlAttributes: new { @class = "form-control" })
                                            @Html.ValidationMessageFor(model => model.TiethocThMa, "", new { @class = "text-danger" })
                                        </div>

                                        <div class="col-md-6">
                                            @Html.LabelFor(model => model.CanboCbMa, "Cán Bộ", htmlAttributes: new { @class = "control-label" })
                                            @Html.DropDownList("CanboCbMa", null, htmlAttributes: new { @class = "form-control" })
                                            @Html.ValidationMessageFor(model => model.CanboCbMa, "", new { @class = "text-danger" })
                                        </div>

                                        <div class="col-md-6">
                                            @Html.LabelFor(model => model.HockyHkMa, "Học Kỳ", htmlAttributes: new { @class = "control-label" })
                                            @Html.DropDownList("HockyHkMa", null, htmlAttributes: new { @class = "form-control" })
                                            <br />
                                            @Html.ValidationMessageFor(model => model.HockyHkMa, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                </div>

                                <div class="form-group" style="text-align: left;">
                                    <div style=" padding-left: 30px;">
                                        <input type="submit" value="Tạo" class="btn btn-default" /> |
                                        <a href="@Url.Action("Index", "Thoikhoabieu")" class=" btn btn-custon-rounded-three btn-primary"><i class="fa fa-undo"></i></a>
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Views/THOIKHOABIEUx/Delete.cshtml
@model QLTHPT.Models.Thoikhoabieu

@{
    ViewBag.Title = "Delete";
}

<div class="data-table-area mg-b-15">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <div class="sparkline13-list shadow-reset">
                    <div class="sparkline13-hd">
                        <div class="main-sparkline13-hd">
                            <h4>
                                <strong>
                                    Xóa
                                </strong>
                            </h4>

                        </div>
                    </div>
                    <h5>Bạn có chắc muốn xóa ?</h5>
                    <div class="sparkline10-graph">
                        <div class="card-body">
                            <table id="bootstrap-data-table" class="table table-striped table-bordered">
                                <thead>
                                    <tr>
                                        <th>
                                            Mã TKB
                                        </th>
                                        <th>
                                            Cán Bộ
                                        </th>
                                        <th>Học Kỳ</th>
                                        <th>Lớp</th>
                                        <th>Môn Học</th>
                                        <th>Tiết Học</th>
                                        <th>Thứ</th>
                                    </tr>
                                    <tr>

                                        <td>@Html.DisplayFor(model => model.TkbMa)</td>
                                        <td>
                                            @Html.DisplayFor(model => model.CanboCbMa)
                                        </td>
                                        <td>@Html.DisplayFor(model => model.HockyHkMa)</td>
                                        <td>
                                            @Html.DisplayFor(model => model.LopLopMa)
                                        </td>
                                        <td>@Html.DisplayFor(model => model.MonhocMhMa)</td>
                                        <td>@Html.DisplayFor(model => model.TiethocThMa)</td>
                                        <td>@Html.DisplayFor(model => model.ThuThuMa)</td>
                                    </tr>
                                </thead>

                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="Xóa" class="btn btn-default" /> |
        <a href="@Url.Action("Index", "Thoikhoabieu")" class=" btn btn-custon-rounded-three btn-primary"><i class="fa fa-undo"></i></a>
    </div>
}

Views/THOIKHOABIEUx/Details.cshtml
@model QLTHPT.Models.Thoikhoabieu

@{
    ViewBag.Title = "Details";
}

<div class="data-table-area mg-b-15">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <div class="sparkline13-list shadow-reset">
                    <div class="sparkline13-hd">
                        <div class="main-sparkline13-hd">
                            <h4>
                                <strong>
                                    Chi Tiết
                                </strong>
                            </h4>
                        </div>
                    </div>
                    <div class="sparkline10-graph">
                        <div class="card-body">
                            <table id="bootstrap-data-table" class="table table-striped table-bordered">
                                <thead>
                                    <tr>
                                        <th>
                                            Mã TKB
                                        </th>
                                        <th>
                                            Cán Bộ
                                        </th>
                                        <th>
                                            Học Kỳ
                                        </th>
                                        <th>
                                            Lớp
                                        </th>
                                        <th>
                                            Môn Học
                                        </th>
                                        <th>
                                            Thứ
                                        </th>
                                        <th>
                                            Tiết Học
                                        </th>                                      
                                    </tr>
                                <tr>
                                    <td>
                                        @Html.DisplayFor(model => model.TkbMa)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(model => model.CanboCbMa)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(model => model.HockyHkMa)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(model => model.LopLopMa)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(model => model.MonhocMhMa)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(model => model.ThuThuMa)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(model => model.TiethocThMa)
                                    </td>                                   
                                </tr>
                                </thead>

                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<p>
    <a href="@Url.Action("Edit", "Thoikhoabieu", new { id = Model.TkbMa })" class="btn btn-custon-rounded-three btn-warning"><i class="fa fa-edit"></i></a> |
    <a href="@Url.Action("Index", "Thoikhoabieu")" class=" btn btn-custon-rounded-three btn-primary"><i class="fa fa-undo"></i></a>
</p>

Views/THOIKHOABIEUx/Edit.cshtml
@model QLTHPT.Models.Thoikhoabieu

@{
    ViewBag.Title = "Edit";
}

<div class="data-table-area mg-b-15">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <div class="sparkline13-list shadow-reset">
                    <div class="sparkline13-hd">
                        <div class="main-sparkline13-hd">
                            <h4><strong>Chỉnh Sửa</strong></h4>

                        </div>
                    </div>
                    <div class="sparkline13-graph">
                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-horizontal">
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                @Html.HiddenFor(model => model.TkbMa)
                                <div class="form-group-inner" style="text-align: left;">
                                    <div class="col-md-12" style="text-align: left;">
                                        @Html.LabelFor(model => model.TkbMa, "Mã", htmlAttributes: new { @class = "control-label" })
                                        @Html.EditorFor(model => model.TkbMa, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                                        @Html.ValidationMessageFor(model => model.TkbMa, "", new { @class = "text-danger" })
                                    </div>

                                    <div class="col-md-6">
                                        @Html.LabelFor(model => model.LopLopMa, "Lớp", htmlAttributes: new { @class = "control-label" })
                                        @Html.DropDownList("LopLopMa", null, htmlAttributes: new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.LopLopMa, "", new { @class = "text-danger" })
                                    </div>

                                    <div class="col-md-6">
                                        @Html.LabelFor(model => model.MonhocMhMa, "Môn", htmlAttributes: new { @class = "control-label" })
                                        @Html.DropDownList("MonhocMhMa", null, htmlAttributes: new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.MonhocMhMa, "", new { @class = "text-danger" })
                                    </div>

                                    <div class="col-md-6">
                                        @Html.LabelFor(model => model.ThuThuMa, "Thứ", htmlAttributes: new { @class = "control-label" })
                                        @Html.DropDownList("ThuThuMa", null, htmlAttributes: new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.ThuThuMa, "", new { @class = "text-danger" })
                                    </div>

                                    <div class="col-md-6">
                                        @Html.LabelFor(model => model.TiethocThMa, "Tiết", htmlAttributes: new { @class = "control-label" })
                                        @Html.DropDownList("TiethocThMa", null, htmlAttributes: new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.TiethocThMa, "", new { @class = "text-danger" })
                                    </div>

                                    <div class="col-md-6">
                                        @Html.LabelFor(model => model.CanboCbMa, "Cán Bộ", htmlAttributes: new { @class = "control-label" })
                                        @Html.DropDownList("CanboCbMa", null, htmlAttributes: new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.CanboCbMa, "", new { @class = "text-danger" })
                                    </div>

                                    <div class="col-md-6">
                                        @Html.LabelFor(model => model.HockyHkMa, "Học Kỳ", htmlAttributes: new { @class = "control-label" })
                                        @Html.DropDownList("HockyHkMa", null, htmlAttributes: new { @class = "form-control" })
                                        <br />
                                        @Html.ValidationMessageFor(model => model.HockyHkMa, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                            <div class="form-group" style="text-align: left;">
                                <div style=" padding-left: 30px;">
                                    <input type="submit" value="Lưu" class="btn btn-default" /> |
                                    <a href="@Url.Action("Index", "Thoikhoabieu")" class=" btn btn-custon-rounded-three btn-primary"><i class="fa fa-undo"></i></a>
                                </div>
                            </div>
                        </div>
                    }
                    </div>
                </div>
            </div>
        </div>
    </div>
 </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

Views/THOIKHOABIEUx/Index.cshtml
@model IEnumerable<QLTHPT.Models.THOIKHOABIEU>

@{
    ViewBag.Title = "Index";
}

<div class="data-table-area mg-b-15">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <div class="sparkline13-list shadow-reset">
                    <div class="sparkline13-hd">
                        <div class="main-sparkline13-hd">
                            <h4><strong>THỜI KHÓA BIỂU</strong></h4>

                        </div>
                    </div>
                    <div class="sparkline13-graph">
                        <div class="datatable-dashv1-list custom-datatable-overright">
                            <div id="toolbar">
                                <strong>@Html.ActionLink("Tạo Mới", "Create")</strong>

                            </div>
                            <table id="table" data-toggle="table" data-search="true" data-key-events="true" data-resizable="true" data-cookie="true" data-cookie-id-table="saveId" data-click-to-select="true" data-toolbar="#toolbar">
                                <thead>
                                    <tr>
                                        <th data-width="100px">
                                            Mã TKB
                                        </th>
                                        <th>
                                            Cán Bộ
                                        </th>
                                        <th>
                                            Học Kỳ
                                        </th>
                                        <th>
                                            Lớp
                                        </th>
                                        <th>
                                            Môn Học
                                        </th>
                                        <th>
                                            Thứ
                                        </th>
                                        <th>
                                            Tiết Học
                                        </th>
                                        <th data-width="150px"></th>
                                    </tr>
                                </thead>
                                <tbody>

                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.TKB_MA)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.CANBO.CB_HOTEN)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.HOCKY.HK_TEN)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.LOP.LOP_TEN)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.MONHOC.MH_TEN)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.TIETHOC.TH_TEN)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.THU.THU_TEN)
                                            </td>
                                            <td>
                                                <a href="@Url.Action("Details", "THOIKHOABIEUx", new { id = item.TKB_MA })" class="btn btn-custon-rounded-three btn-success"><i class="fa fa-info-circle"></i></a>
                                                <a href="@Url.Action("Edit", "THOIKHOABIEUx", new { id = item.TKB_MA })" class="btn btn-custon-rounded-three btn-warning"><i class="fa fa-edit"></i></a>
                                                <a href="@Url.Action("Delete", "THOIKHOABIEUx", new { id = item.TKB_MA })" class="btn btn-custon-rounded-three btn-danger"><i class="fa fa-trash"></i></a>

                                            </td>
                                        </tr>
                                    }

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>