Models/Bacluong.cs
using System;
using System.Collections.Generic;

namespace qlthpt.Models
{
    public partial class Bacluong
    {
        public Bacluong()
        {
            Thongtinluong = new HashSet<Thongtinluong>();
        }

        public string BlMa { get; set; }
        public string BlTen { get; set; }

        public virtual ICollection<Thongtinluong> Thongtinluong { get; set; }
    }
}

Controllers/BACLUONGsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using qlthpt.Models;

namespace QLTHPT.Controllers
{
    public class BACLUONGsController : Controller
    {
        private acomptec_qlthptContext db = new acomptec_qlthptContext();

        // GET: BACLUONGs
        public ActionResult Index()
        {
            return View(db.Bacluong.ToList());
        }


    }
}

Views/BACLUONGs/Index.cshtml
@model IEnumerable<qlthpt.Models.Bacluong>

@{
    ViewBag.Title = "Index";
}

<div class="data-table-area mg-b-15">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <div class="sparkline13-list shadow-reset">
                    <div class="sparkline13-hd">
                        <div class="main-sparkline13-hd">
                            <h4><strong>BẬC LƯƠNG</strong></h4>
                        </div>
                    </div>
                    <div class="sparkline13-graph">
                        <div class="datatable-dashv1-list custom-datatable-overright">
                            <div id="toolbar">
                                <strong>@Html.ActionLink("Tạo Mới", "Create")</strong>
                            </div>
                            @*<table id="table" data-toggle="table" data-search="true" data-key-events="true" data-resizable="true" data-cookie="true" data-cookie-id-table="saveId" data-click-to-select="true" data-toolbar="#toolbar">*@
                            <table id="table" data-resizable="false" data-toggle="table" data-pagination="true" data-search="true" data-cookie="true" data-cookie-id-table="saveId" data-click-to-select="true" data-toolbar="#toolbar">
                                <thead>
                                    <tr>
                                        <th data-width="100px">
                                            Mã Bậc Lương
                                        </th>
                                        <th>
                                            Bậc Lương
                                        </th>
                                        <th data-width="200px"></th>
                                    </tr>
                                </thead>
                                <tbody>

                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.BlMa)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.BlTen)
                                            </td>
                                            <td>
                                                <a href="@Url.Action("Details", "BACLUONGs", new { id = item.BlMa })" class="btn btn-custon-rounded-three btn-success"><i class="fa fa-info-circle"></i></a>
                                                <a href="@Url.Action("Edit", "BACLUONGs", new { id = item.BlMa })" class="btn btn-custon-rounded-three btn-warning"><i class="fa fa-edit"></i></a>
                                                <a href="@Url.Action("Delete", "BACLUONGs", new { id = item.BlMa })" class="btn btn-custon-rounded-three btn-danger"><i class="fa fa-trash"></i></a>
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>

                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>