Models/Chuyennganh.cs
using System;
using System.Collections.Generic;

namespace qlthpt.Models
{
    public partial class Chuyennganh
    {
        public Chuyennganh()
        {
            Thongtindaotao = new HashSet<Thongtindaotao>();
        }

        public string CnMa { get; set; }
        public string CnTen { get; set; }

        public virtual ICollection<Thongtindaotao> Thongtindaotao { get; set; }
    }
}

Controllers/ChuyennganhsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using qlthpt.Models;

namespace qlthpt.Controllers
{
    public class ChuyennganhsController : Controller
    {
        private acomptec_qlthptContext _context;

        public ChuyennganhsController(acomptec_qlthptContext context)
        {
            _context = context;
        }

        // GET: Chuyennganhs
        public async Task<IActionResult> Index()
        {
            return View(await _context.Chuyennganh.ToListAsync());
        }

        // GET: Chuyennganhs/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var chuyennganh = await _context.Chuyennganh
                .FirstOrDefaultAsync(m => m.CnMa == id);
            if (chuyennganh == null)
            {
                return NotFound();
            }

            return View(chuyennganh);
        }

        // GET: Chuyennganhs/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Chuyennganhs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CnMa,CnTen")] Chuyennganh chuyennganh)
        {
            if (ModelState.IsValid)
            {
                _context.Add(chuyennganh);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(chuyennganh);
        }

        // GET: Chuyennganhs/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var chuyennganh = await _context.Chuyennganh.FindAsync(id);
            if (chuyennganh == null)
            {
                return NotFound();
            }
            return View(chuyennganh);
        }

        // POST: Chuyennganhs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("CnMa,CnTen")] Chuyennganh chuyennganh)
        {
            if (id != chuyennganh.CnMa)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(chuyennganh);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ChuyennganhExists(chuyennganh.CnMa))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(chuyennganh);
        }

        // GET: Chuyennganhs/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var chuyennganh = await _context.Chuyennganh
                .FirstOrDefaultAsync(m => m.CnMa == id);
            if (chuyennganh == null)
            {
                return NotFound();
            }

            return View(chuyennganh);
        }

        // POST: Chuyennganhs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var chuyennganh = await _context.Chuyennganh.FindAsync(id);
            _context.Chuyennganh.Remove(chuyennganh);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ChuyennganhExists(string id)
        {
            return _context.Chuyennganh.Any(e => e.CnMa == id);
        }
    }
}

Views/Chuyennganhs/Create.cshtml
@model qlthpt.Models.Chuyennganh

@{
    ViewBag.Title = "Create";
}

<div class="data-table-area mg-b-15">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <div class="sparkline13-list shadow-reset">
                    <div class="sparkline13-hd">
                        <div class="main-sparkline13-hd">
                            <h4><strong>Tạo Mới</strong></h4>
                        </div>
                    </div>
                    <div class="sparkline13-graph">
                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-horizontal">
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                <div class="form-group-inner">
                                    @Html.LabelFor(model => model.CnMa, "Mã", htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.CnMa, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                                        <br />
                                        @Html.ValidationMessageFor(model => model.CnMa, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group-inner">
                                    @Html.LabelFor(model => model.CnTen, "Tên", htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.CnTen, new { htmlAttributes = new { @class = "form-control" } })
                                        <br />
                                        @Html.ValidationMessageFor(model => model.CnTen, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="col-md-offset-2 col-md-10">
                                        <input type="submit" value="Tạo" class="btn btn-default" /> |
                                        <a href="@Url.Action("Index", "CHUYENNGANHs")" class=" btn btn-custon-rounded-three btn-primary"><i class="fa fa-undo"></i></a>
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Views/Chuyennganhs/Details.cshtml
@model qlthpt.Models.Chuyennganh

@{
    ViewBag.Title = "Details";
}

<div class="data-table-area mg-b-15">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <div class="sparkline13-list shadow-reset">
                    <div class="sparkline13-hd">
                        <div class="main-sparkline13-hd">
                            <h4>
                                <strong>
                                    Chi Tiết
                                </strong>
                            </h4>
                        </div>
                    </div>
                    <div class="sparkline10-graph">
                        <div class="card-body">
                            <table id="bootstrap-data-table" class="table table-striped table-bordered">
                                <thead>
                                    <tr>
                                        <th>
                                            Mã
                                        </th>
                                        <th>
                                            Tên
                                        </th>

                                    </tr>
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(model => model.CnMa)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(model => model.CnTen)
                                        </td>

                                    </tr>
                                </thead>

                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<p>
    <a href="@Url.Action("Edit", "CHUYENNGANHs", new { id = Model.CnMa})" class="btn btn-custon-rounded-three btn-warning"><i class="fa fa-edit"></i></a> |
    <a href="@Url.Action("Index", "CHUYENNGANHs")" class=" btn btn-custon-rounded-three btn-primary"><i class="fa fa-undo"></i></a>
</p>

Views/Chuyennganhs/Edit.cshtml
@model qlthpt.Models.Chuyennganh

@{
    ViewBag.Title = "Edit";
}

    <div class="data-table-area mg-b-15">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="sparkline13-list shadow-reset">
                        <div class="sparkline13-hd">
                            <div class="main-sparkline13-hd">
                                <h4><strong>Chỉnh Sửa</strong></h4>
                            </div>
                        </div>
                        <div class="sparkline13-graph">
                            @using (Html.BeginForm())
                            {
                                @Html.AntiForgeryToken()

                                <div class="form-horizontal">
                                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                    @Html.HiddenFor(model => model.CnMa)
                                    <div class="form-group-inner">
                                        @Html.LabelFor(model => model.CnMa, "Mã", htmlAttributes: new { @class = "control-label col-md-2" })
                                        <div class="col-md-10">
                                            @Html.EditorFor(model => model.CnMa, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                                            <br />
                                            @Html.ValidationMessageFor(model => model.CnMa, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="form-group-inner">
                                        @Html.LabelFor(model => model.CnTen, "Lớp", htmlAttributes: new { @class = "control-label col-md-2" })
                                        <div class="col-md-10">
                                            @Html.EditorFor(model => model.CnTen, new { htmlAttributes = new { @class = "form-control" } })
                                            <br />
                                            @Html.ValidationMessageFor(model => model.CnTen, "", new { @class = "text-danger" })
                                        </div>
                                    </div>


                                    <div class="form-group">
                                        <div class="col-md-offset-2 col-md-10">
                                            <input type="submit" value="Lưu" class="btn btn-default" /> |
                                            <a href="@Url.Action("Index", "CHUYENNGANHs")" class=" btn btn-custon-rounded-three btn-primary"><i class="fa fa-undo"></i></a>
                                        </div>
                                    </div>
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

Views/Chuyennganhs/Index.cshtml
@model IEnumerable<qlthpt.Models.Chuyennganh>

@{
    ViewBag.Title = "Index";
}

<div class="data-table-area mg-b-15">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <div class="sparkline13-list shadow-reset">
                    <div class="sparkline13-hd">
                        <div class="main-sparkline13-hd">
                            <h4><strong>CHUYÊN NGÀNH</strong></h4>
                        </div>
                    </div>
                    <div class="sparkline13-graph">
                        <div class="datatable-dashv1-list custom-datatable-overright">
                            <div id="toolbar">
                                <strong>@Html.ActionLink("Tạo Mới", "Create")</strong>
                            </div>
                            <table id="table" data-toggle="table" data-search="true" data-key-events="true" data-resizable="true" data-cookie="true" data-cookie-id-table="saveId" data-click-to-select="true" data-toolbar="#toolbar">
                                <thead>
                                    <tr>
                                        <th>
                                            Mã
                                        </th>
                                        <th>
                                            Tên
                                        </th>

                                        <th>

                                        </th>
                                    </tr>
                                </thead>
                                <tbody>

                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.CnMa)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.CnTen)
                                            </td>
                                            <td>
                                                <a href="@Url.Action("Details", "Chuyennganhs", new { id = item.CnMa })" class="btn btn-custon-rounded-three btn-success"><i class="fa fa-info-circle"></i></a>
                                                <a href="@Url.Action("Edit", "Chuyennganhs", new { id = item.CnMa })" class="btn btn-custon-rounded-three btn-warning"><i class="fa fa-edit"></i></a>
                                                <a href="@Url.Action("Delete", "Chuyennganhs", new { id = item.CnMa })" class="btn btn-custon-rounded-three btn-danger"><i class="fa fa-trash"></i></a>
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>

                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>